/* ---------------- Month-End Close ---------------- */
async function viewClose(root) {
  const opt = await read("site/options");
  const months = opt.close_months;
  if (!state.closeMonth) state.closeMonth = opt.close_default;
  const d = await read("close/" + state.closeMonth);
  const money = v => usd(v, 2);
  const st = s => { const [c, t] = STATUS[s] || ["p-info", s]; return pill(c, t); };
  const diffCell = v => `<td class="r num ${Math.abs(v) < .005 ? "muted" : "down"}">${Math.abs(v) < .005 ? "0.00" : money(v)}</td>`;
  const blocking = d.blocking_count;
  root.innerHTML = `
  <section><div class="bar"><div style="flex:1 1 280px"><h2>Month-End Close</h2><p class="lead" style="margin:0">The nine month-end inputs go through the allocation rules into a Business Central journal and AR invoices, with control totals at each step. Rules version ${esc(d.rules_version)}.</p></div>
    <label class="f">Month<select id="cm-sel">${months.map(x => `<option value="${x.month}">${esc(x.label)}${x.complete ? "" : " (in progress)"}</option>`).join("")}</select></label></div></section>
  <section>${blocking ? `<div class="banner bad">${blocking} error${blocking > 1 ? "s" : ""} block approval. Resolve them or approve with an override note in the working app.</div>` : `<div class="banner" style="background:var(--good-soft);color:var(--good)">No blocking errors. This close is ready to approve in the working app.</div>`}
    <div class="steps" style="margin-top:12px">${d.stages.map((s, i) => `<div class="card step"><b>${esc(s.label)}</b>${st(s.status)}<small>${esc(s.detail || "")}</small></div>`).join("")}</div></section>
  <section><h2>Sources</h2><p class="lead">What arrived, and what the rules did with it.</p><div class="card scroll"><table><thead><tr><th>Source</th><th>Status</th><th class="r">Rows</th><th class="r">File total</th><th class="r">Journal total</th><th>Detail</th></tr></thead><tbody>
    ${d.sources.map(s => `<tr><td><b>${esc(s.label)}</b><br><span class="muted" style="font-size:12px">${esc(s.workflow)}</span></td><td>${st(s.status)}</td><td class="r num">${nf(s.rows)}</td><td class="r num">${s.file_total == null ? "n/a" : money(s.file_total)}</td><td class="r num">${s.journal_total == null ? "n/a" : money(s.journal_total)}</td><td class="muted">${esc(s.detail)}${s.exceptions ? ` · ${s.exceptions} exception${s.exceptions > 1 ? "s" : ""}` : ""}</td></tr>`).join("")}</tbody></table></div></section>
  <section><h2>Control totals</h2><p class="lead">Source file to loaded to rules output to journal. Differences must be zero or explained.</p><div class="card scroll"><table><thead><tr><th>Source</th><th>Measure</th><th class="r">File</th><th class="r">Loaded</th><th class="r">Rules</th><th class="r">Journal</th><th class="r">Diff</th><th>Status</th></tr></thead><tbody>
    ${d.control_totals.map(c => `<tr><td class="mono">${esc(c.source)}</td><td>${esc(c.measure)}</td><td class="r num">${money(c.file_total)}</td><td class="r num">${money(c.loaded_total)}</td><td class="r num">${money(c.rules_total)}</td><td class="r num">${money(c.journal_total)}</td>${diffCell(c.diff_file_loaded + c.diff_loaded_rules + c.diff_rules_journal)}<td>${pill(c.status === "ok" ? "p-ok" : "p-bad", c.status === "ok" ? "OK" : "Break")}</td></tr>`).join("")}</tbody></table></div></section>
  <section><h2>Business Central journal</h2><p class="lead">General Journal batch GENERAL / ECOM. ${d.journal.balanced ? "Every document balances." : esc(d.journal.unbalanced_documents + " document(s) do not balance.")} Total debits ${money(d.journal.total_debit)}, credits ${money(d.journal.total_credit)}. Open a document to see its lines.</p>
    <div class="card">${d.journal.documents.map(doc => `<details><summary><b class="mono">${esc(doc.document_no)}</b>${pill(doc.balanced ? "p-ok" : "p-bad", doc.balanced ? "Balanced" : "Unbalanced")}${doc.has_placeholder_accounts ? pill("p-warn", "Placeholder accounts") : ""}<span class="muted">${doc.line_count} lines · ${money(doc.total_debit)}</span></summary>
      <div class="scroll"><table><thead><tr><th>Account</th><th>Description</th><th>Dept</th><th class="r">Debit</th><th class="r">Credit</th></tr></thead><tbody>${doc.lines.map(l => `<tr><td class="mono">${esc(l.account_no)}${l.placeholder_account ? " *" : ""}</td><td>${esc(l.description)}</td><td class="mono">${esc(l.department_code)}</td><td class="r num">${l.debit ? money(l.debit) : ""}</td><td class="r num">${l.credit ? money(l.credit) : ""}</td></tr>`).join("")}</tbody></table></div></details>`).join("")}</div>
    <p class="muted" style="margin:8px 0 0;font-size:12.5px">* Placeholder account. Goodwill has not yet confirmed its chart of accounts for revenue, fees and receivables.</p></section>
  <section><h2>Parallel run against the manual workbook</h2><p class="lead">${d.comparison.status === "no_workbook" || !d.comparison.workbook ? "No manual workbook was supplied for this month." : `${nf(d.comparison.matches)} lines match the workbook. ${d.comparison.differences.length} differ.`}</p>
    ${d.comparison.differences.length ? `<div class="card scroll"><table><thead><tr><th>Document</th><th>Account</th><th>Description</th><th class="r">System</th><th class="r">Workbook</th><th class="r">Difference</th></tr></thead><tbody>${d.comparison.differences.map(x => `<tr><td class="mono">${esc(x.doc_no)}</td><td class="mono">${esc(x.account_no)}</td><td>${esc(x.description)}</td><td class="r num">${x.system_amount == null ? "—" : money(x.system_amount)}</td><td class="r num">${x.workbook_amount == null ? "—" : money(x.workbook_amount)}</td><td class="r num down">${x.difference == null ? "" : money(x.difference)}</td></tr>`).join("")}</tbody></table></div>` : ""}</section>
  <section><h2>AR invoices</h2><div class="card scroll"><table><thead><tr><th>Customer</th><th>Document</th><th class="r">Lines</th><th class="r">Total</th><th>Ties out</th></tr></thead><tbody>
    ${d.invoices.map(i => `<tr><td>${esc(i.customer_name)} ${i.placeholder ? pill("p-warn", "Placeholder customer") : ""}</td><td class="mono">${esc(i.external_document_number)}</td><td class="r num">${i.lines}</td><td class="r num">${money(i.total)}</td><td>${pill(i.ties_out ? "p-ok" : "p-bad", i.ties_out ? "Yes" : "No")}</td></tr>`).join("")}</tbody></table></div></section>
  <section><h2>Customer balances</h2><p class="lead">Invoice − fees − refunds − payouts = open balance, per marketplace.</p><div class="card scroll"><table><thead><tr><th>Marketplace</th><th class="r">Invoice</th><th class="r">Fees</th><th class="r">Refunds</th><th class="r">Payouts</th><th class="r">Open balance</th><th>Status</th></tr></thead><tbody>
    ${d.customer_balances.map(b => `<tr><td>${esc(b.channel)}</td><td class="r num">${money(b.invoice_total)}</td><td class="r num">${money(b.fees)}</td><td class="r num">${money(b.refunds)}</td><td class="r num">${money(b.payouts)}</td><td class="r num">${money(b.open_balance)}</td><td>${pill(b.status === "ok" ? "p-ok" : "p-bad", b.status === "ok" ? "OK" : "Break")}</td></tr>`).join("")}</tbody></table></div></section>
  <section><h2>Exceptions</h2><p class="lead">Every exception has an owner. Errors block approval.</p><div class="card scroll"><table><thead><tr><th>Severity</th><th>Source</th><th>What happened</th><th class="r">Amount</th><th>Owner</th></tr></thead><tbody>
    ${d.exceptions.length ? [...d.exceptions].sort((a, b) => ({error: 0, warning: 1, info: 2}[a.severity] ?? 3) - ({error: 0, warning: 1, info: 2}[b.severity] ?? 3)).map(e => `<tr><td>${pill(e.severity === "error" ? "p-bad" : e.severity === "warning" ? "p-warn" : "p-info", e.severity)}</td><td class="mono">${esc(e.source)}</td><td>${esc(e.message)}</td><td class="r num">${e.amount == null ? "" : money(e.amount)}</td><td>${esc(e.owner)}</td></tr>`).join("") : `<tr><td colspan="5" class="empty">No exceptions.</td></tr>`}</tbody></table></div></section>`;
  $("#cm-sel", root).value = state.closeMonth;
  $("#cm-sel", root).onchange = e => { state.closeMonth = e.target.value; render(); };
}
registerTab("close", "Month-End Close", viewClose, 70);
