"""PDF -> tables, without AI when the PDF has a text layer (statements and invoices generated by a system do).

1. Header-anchored tables: find a line that carries a known layout's column headers ('Line Date Type Order No SKU
   Description Amount'), take each header's position as a column, and read the following lines into those columns
   until the table ends. Works on the plain text tables most statements use, across page breaks (the header repeats).
2. Ruled tables (cell borders drawn): pdfplumber's own table finder.
3. Printed values outside the tables ('Net payment  $2,894.20', 'Statement period: September 2026') are kept as
   `stated`: the loader uses them as control totals.

A scanned PDF (no text layer) yields nothing here; the caller then asks Claude, and marks the result for review.
"""
from __future__ import annotations

import io
import re
from dataclasses import dataclass, field

from .tabular import clean_header

LINE_TOLERANCE = 3.0          # words whose tops differ by less than this (points) are on the same line
MAX_HEADER_WORDS = 6          # longest printed column name we try to match ('Express or Ground Tracking ID')
PAGE_FOOTER = re.compile(r"(?i)^\s*(page\s*)?\d+\s*(of|/)\s*\d+\s*$")
MONEY = r"\(?-?\$?\s?-?[\d,]+\.\d{2}\)?"


@dataclass
class Word:
    text: str
    x0: float
    x1: float
    top: float
    height: float = 8.0

    @property
    def mid(self) -> float:
        return (self.x0 + self.x1) / 2


@dataclass
class PdfRead:
    tables: list[dict] = field(default_factory=list)   # {header, rows, layout, pages}
    stated: dict[str, str] = field(default_factory=dict)
    text: str = ""
    pages: int = 0


def _norm(s: str) -> str:
    return re.sub(r"[^a-z0-9#&]", "", s.lower())


def _lines(page) -> list[list[Word]]:
    words = [Word(w["text"], w["x0"], w["x1"], w["top"], w["bottom"] - w["top"])
             for w in page.extract_words(x_tolerance=1.5, y_tolerance=2, keep_blank_chars=False)]
    words.sort(key=lambda w: (round(w.top), w.x0))
    lines: list[list[Word]] = []
    for w in words:
        if lines and abs(lines[-1][0].top - w.top) <= LINE_TOLERANCE:
            lines[-1].append(w)
        else:
            lines.append([w])
    return [sorted(ln, key=lambda w: w.x0) for ln in lines]


def _line_text(ln: list[Word]) -> str:
    return " ".join(w.text for w in ln)


def _match_header(ln: list[Word], names: dict[str, str]) -> list[tuple[str, float, float]] | None:
    """[(column, x0, x1)] for every known header name found as consecutive words on this line, left to right.
    `names` maps a normalized printed name (column or alias) to the layout's column."""
    found, i = [], 0
    while i < len(ln):
        hit = None
        for k in range(min(MAX_HEADER_WORDS, len(ln) - i), 0, -1):       # longest phrase first: 'Order No' before 'Order'
            key = _norm("".join(w.text for w in ln[i:i + k]))
            if key in names:
                hit = (names[key], ln[i].x0, ln[i + k - 1].x1, k)
                break
        if hit:
            found.append(hit[:3])
            i += hit[3]
        else:
            i += 1
    cols = [c for c, _, _ in found]
    return found if len(cols) == len(set(cols)) else None


def _phrases(ln: list[Word]) -> list[Word]:
    """Words separated by about one space are one phrase (one cell's text). Columns are separated by wider gaps."""
    out: list[Word] = []
    for w in ln:
        if out and w.x0 - out[-1].x1 <= 0.5 * max(w.height, 1.0):
            p = out[-1]
            out[-1] = Word(f"{p.text} {w.text}", p.x0, w.x1, p.top, p.height)
        else:
            out.append(w)
    return out


def _cells(ln: list[Word], bounds: list[tuple[str, float, float]]) -> list[str]:
    """Split a line into the header's columns. Each phrase goes, whole, to the column whose span its centre falls
    in; the boundary between two columns is halfway between the end of one header and the start of the next.
    Placing phrases rather than words keeps a long description out of a right-aligned amount column next to it."""
    cuts = [(bounds[i][2] + bounds[i + 1][1]) / 2 for i in range(len(bounds) - 1)]
    cells = [[] for _ in bounds]
    for w in _phrases(ln):
        idx = next((i for i, c in enumerate(cuts) if w.mid < c), len(bounds) - 1)
        cells[idx].append(w.text)
    return [" ".join(c) for c in cells]


def _anchored(pages: list[list[list[Word]]], layout: dict) -> dict | None:
    """Rows under `layout`'s header line on every page. A row needs every required column filled; a line with only
    one cell right after a row is a wrapped continuation of that cell; anything else ends the table on that page."""
    names = {_norm(c): c for c in layout["columns"]}
    names.update({_norm(a): c for a, c in layout.get("aliases", {}).items() if c in layout["columns"]})
    required = set(layout.get("required") or [])
    header, rows, used_pages, used_lines = None, [], [], set()
    for pno, lines in enumerate(pages, 1):
        bounds, last_top, gap = None, None, None
        for lno, ln in enumerate(lines):
            if bounds is None:
                b = _match_header(ln, names)
                cols = {c for c, _, _ in b or []}
                if b and required <= cols and len(cols) >= max(2, 0.6 * len(layout["columns"])):
                    bounds = b
                    header = header or [c for c, _, _ in b]
                    if [c for c, _, _ in b] != header:     # a different header on a later page: not the same table
                        bounds = None
                        continue
                    used_pages.append(pno)
                    used_lines.add((pno, lno))
                continue
            cells = _cells(ln, bounds)
            filled = {header[i] for i, c in enumerate(cells) if c}
            top = ln[0].top
            if required <= filled:
                rows.append(cells)
                used_lines.add((pno, lno))
                gap = top - last_top if last_top is not None and gap is None else gap
                last_top = top
            elif (rows and last_top is not None and len(filled) == 1
                  and top - last_top <= 1.5 * (gap or 2 * ln[0].height)        # directly under the row it continues
                  and not re.fullmatch(MONEY, "".join(c for c in cells if c))
                  and not PAGE_FOOTER.match(_line_text(ln))):
                i = next(i for i, c in enumerate(cells) if c)
                rows[-1][i] = f"{rows[-1][i]} {cells[i]}".strip()
                used_lines.add((pno, lno))
                last_top = top
            else:
                bounds = None
    if not rows:
        return None
    return {"header": header, "rows": rows, "layout": layout["id"], "pages": used_pages, "lines": used_lines}


def _stated(pages: list[list[list[Word]]], skip: set) -> dict[str, str]:
    """'Label: value' and 'Label ..... $1,234.56' lines outside the tables, in reading order."""
    out: dict[str, str] = {}
    for pno, lines in enumerate(pages, 1):
        for lno, ln in enumerate(lines):
            if (pno, lno) in skip:
                continue
            text = _line_text(ln)
            m = re.match(rf"^(?P<label>[A-Za-z][A-Za-z0-9 &/#().,'-]{{0,48}}?)\s*[:.]*\s+(?P<val>{MONEY})$", text) \
                or re.match(r"^(?P<label>[A-Za-z][A-Za-z0-9 &/#()'-]{0,48}?)\s*:\s*(?P<val>.+)$", text)
            if m:
                label = m.group("label").strip(" .:")
                if label and label not in out:
                    out[label] = m.group("val").strip()
    return out


def read_pdf(data: bytes, layouts: list[dict]) -> PdfRead:
    import pdfplumber   # imported lazily: only needed when a PDF arrives

    res = PdfRead()
    with pdfplumber.open(io.BytesIO(data)) as pdf:
        res.pages = len(pdf.pages)
        pages = [_lines(p) for p in pdf.pages]
        res.text = "\n\n".join("\n".join(_line_text(ln) for ln in lines) for lines in pages)
        if not res.text.strip():
            return res                                   # scanned: no text layer
        # Several layouts can claim the same header line (the bank layout's 'Date / Type / Description / Amount' are
        # also statement columns): the layout that matches the most of the printed headers wins.
        cands = [(t, len(layout["columns"])) for layout in layouts if (t := _anchored(pages, layout))]
        cands.sort(key=lambda tc: (len(tc[0]["header"]), len(tc[0]["header"]) / tc[1]), reverse=True)
        used: set = set()
        for t, _ in cands:
            if not (t["lines"] & used):
                used |= t["lines"]
                res.tables.append(t)
        if not res.tables:
            for pno, page in enumerate(pdf.pages, 1):
                for raw in page.extract_tables():
                    rows = [[(c or "").replace("\n", " ").strip() for c in r] for r in raw if any(c for c in r)]
                    if len(rows) >= 2 and len(rows[0]) >= 2:
                        res.tables.append({"header": clean_header(rows[0]), "rows": rows[1:], "layout": None,
                                           "pages": [pno], "lines": set()})
        res.stated = _stated(pages, used)
    return res
